@inject('config', 'ScottNason\EcoHelpers\Classes\ehConfig')
{{--
///////////////////////////////////////////////////////////////////////////////////////
WARNING!
This is the base template for all pages so be very mindful (think twice)
about making any changes to this file.
    -- Most changes are done using the config/eco-helpers configuration file to specify
       the user editable site layout files contained in the views/echoHelpers/_layouts folder.

This app master templates's function is to block out a "standard" html page that you "extend" in
individual page templates:

///////////////////////////////////////////////////////////////////////////////////////
- HTML document type and base page layout.
- Includes the user configurable files (defined in eco-helpers.php):
    - head_file
    - navbar_file
    - footer_file

///////////////////////////////////////////////////////////////////////////////////////
- This master template @yields these areas for "extended" page use:

    - additional-head       - Anything else you need in the <head> section can be added here.
                            - Often used for per page <style> assignments.
    - main-content          - The whole body of page - WITHOUT any doctype declarations or head section.
    - per-page-js           - Any javascript needed for a single page.
--}}
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    {{--
        Include any head elements defined in eco-helpers.php layout.head_file.
        --}}
@if(View::exists($config::get('layout.head_file')))
@include($config::get('layout.head_file'))
@endif
    {{--
        Include the CSS autoloader mechanism. This pulls in the level-0 (global) css links from the published
        views/ecoHelpers/autolaod/0-css-autoload.blade.php and then any page specific css called
        by the ehLayout::setAutoload(nn) from the Controller.
        --}}
    @include('ecoHelpers::core.eh-css-loader')
    {{--
        The <title> of the page. This will pull automatically from the eh_pages table
        when it is set and can be overriden or manually set by ehLayout::setTitle('title').
        --}}
    @if (!empty($form['layout']['title']['content']))
        <title>{{ $form['layout']['title']['content'] }}</title>
    @else
        {{-- But if no title in the config file or the eh_pages table, then use the name set in  the .dnv file. --}}
        <title>{{ config('app.name', 'eco-helpers') }}</title>
    @endif
    {{-- The Blade yield block used by other templates to add additional <head> items as needed.
         Commonly used to insert per page <style> elements.
         --}}
    @yield('additional-head')
</head>
<body>
{{--
    Initial check to ensure this template was passed the $form['layout'] array.
    That is generated by getting the ehLayout contents and we can't continue without it.
    --}}
@if(!isset($form['layout']))
    {{ dd("Missing layout array: You must run Layout::initLayout() and pass to the the template as $form[layout]") }}
@endif
{{--
    The per user notification url.
    --}}
<script type="application/javascript">
    var notification_url = '{{config('app.url')}}' + '/notifications';
</script>
{{--
    The per user notificatoin message modal.
    --}}
@include('ecoHelpers::core.eh-message-modal')
{{--
    ### NAVIGATION BAR AREA ###
    This is the user configurable navbar area of the page
    --}}
@if(View::exists($config::get('layout.navbar_file')))
    @include($config::get('layout.navbar_file'))
@endif
{{--
    ### SYSTEM BANNER AREA ###
    The system banner displays on every page right below the navigation banner
    For security reasons; the banner is configuarble to enforce being logged in to view.

    USAGE (uncommon): ehLayout::setBanner('text', 'css-class');
           !! Note this is not commonly called this way since it's globally set in the admin settings !!

    NOTE: We're just setting a $show_banner variable here and then using it below
          to determine the actual visibility of the banner.
    --}}
{{--
    If the configuration says not to check if authorized then
    show banner all the time.
    --}}
@if (!$config::get('layout.options.banner_auth'))
    @php $show_banner = true; @endphp
@else
    {{--
        If the configuration says TO check if authorized then check that first
        and display accordingly.
        --}}
    @if (Auth::check())
        @php $show_banner = true; @endphp
    @else
        @php $show_banner = false; @endphp
    @endif
@endif
{{-- Based on the checks above, decide whether to execute the rest of the show banner checks.
     Is it turned on - and if so, should it blink.
     --}}
@if ($show_banner)
    @if ($form['layout']['banner']['state'])
        @if($form['layout']['banner']['blink'])
            <div id="eh-layout-page-banner" class="{{$form['layout']['banner']['class']}} blink">
                {!! $form['layout']['banner']['content'] !!}
            </div>
        @else
            <div id="eh-layout-page-banner" class="{{$form['layout']['banner']['class']}}">
                {!! $form['layout']['banner']['content'] ?? '' !!}
            </div>
        @endif
    @endif
@endif
{{--
    ### MAIN CONTENT SECTION ###
    Set up a container for the <main> page content just below the system banner.
    Set the main container class in the eco-helpers.layout.options section.
    This can be either "full width" class
    USAGE: There are no direct ehLayout classes to interact with this. Use the individual are calls.
    --}}
@if (!empty($form['layout']['full-width']) && $form['layout']['full-width']['state'])
    @php($main_class = $config::get('layout.options.page_main_class_full'))
@else
    @php($main_class = $config::get('layout.options.page_main_class_normal'))
@endif
<main class="{{$main_class}}">
    {{--
        ### MAIN CONTENT BODY ###
        Yeild the standard page content area for all views to use.
        --}}
    @yield('main-content')
    {{--
        ### JS AUTO-LOADER ###
        Include the Javascript $settinger mechanism.
        --}}
    @include('ecoHelpers::core.eh-js-loader')
    {{--
        ### GLOBAL JS ###
        Global js required by all crud pages.
    --}}
    {{--
        Yield to other templates so they can add additional javascript elements as needed.
        --}}
    @yield('per-page-js')
</main>
{{--
        ### FOOTER AREA ###
        Include the file specified in the eco-helpers config file.
        --}}
@if(View::exists($config::get('layout.footer_file')))
    @include($config::get('layout.footer_file'))
@else
    <p>NO USER FOOTER FILE PRESENT.</p>
    <p><em>Configure filename in config/eco-helpers.php and place the blade template file in
            views/ecoHelpers folder.</em></p>
@endif
</body>
</html>